set-option -g default-terminal "xterm-256color"
set -as terminal-features ",xterm-256color:RGB"

set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

set -g base-index 1
set -g pane-base-index 1

set -g extended-keys on
set -g extended-keys-format csi-u
set -s escape-time 0

unbind C-b
set -g prefix C-a
bind C-a send-prefix

run-shell -b 'tpane'
