require("core.plugins.harpoon")
require("core.plugins.lualine")
require("core.plugins.mason")
require("core.plugins.nvim-tree")
require("core.plugins.nvim-treesitter")
require("core.plugins.telescope")
require("core.plugins.toggleterm")
