use_default_settings: true

server:
  secret_key: "pi-web-search-local"
  limiter: false

search:
  formats:
    - html
    - json

engines:
  - name: wikidata
    disabled: true
  - name: ahmia
    inactive: true
  - name: torch
    inactive: true
  - name: radio browser
    inactive: true
